import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('Agent panel uses the real runtime with reviewed navigation, model evidence, cancel, and no-write boundaries', async () => {
  const source = await readFile(new URL('../src/components/AgentPanel.tsx', import.meta.url), 'utf8');
  assert.match(source, /activationState === "configuration-required"/);
  assert.match(source, /discoverAgentSkills\(\)/);
  assert.match(source, /createNativeAgentRuntime\(\)/);
  assert.match(source, /useAgentThread\(\{/);
  assert.match(source, /runtime\.startTurn\(\{/);
  assert.match(source, /retryOfTurnId/);
  assert.match(source, /upstreamThreadId: state\.runtime\.kind === "codexAppServer"/);
  assert.match(source, /const capturedBinding = binding/);
  assert.match(source, /capturedBinding\.createToolExecutor/);
  assert.match(source, /createDirectApplyToolExecutor/);
  assert.match(source, /const turnId = state\.activeTurnId/);
  assert.match(source, /settleTurn\(turnId, "cancelled"/);
  assert.match(source, /runtime\.cancelTurn\(turnId\)/);
  assert.doesNotMatch(source, /activeRunId/);
  assert.doesNotMatch(source, /AgentChangeReview/);
  assert.match(source, /AgentConversationSelector/);
  assert.match(source, /availableModels: modelOptions/);
  assert.match(source, /reasoningEffort: "standard"/);
  assert.match(source, /selectedSkillIds: \[\]/);
  assert.doesNotMatch(source, /AgentThreadHistory|AgentSkillPicker|archiveThread|showArchivedHistory/);
  assert.match(source, /useExternalStoreRuntime/);
  assert.match(source, /AssistantRuntimeProvider/);
  assert.match(source, /<AgentTranscript/);
  assert.match(source, /useAgentPresentation\(state\)/);
  assert.match(source, /presentation=\{presentation\}/);
  assert.match(source, /<AgentThreadHeader/);
  assert.match(source, /onClose=\{onClose\}/);
  assert.doesNotMatch(source, /ideanote-change/);
  assert.doesNotMatch(source, /IdeaSketchAgentOperation/);
  assert.match(source, /getActiveBinding/);
  assert.doesNotMatch(source, /ThreadPrimitive\.Messages/);
  assert.doesNotMatch(source, /save_file|saveWorkspaceDocument|saveStandaloneDocument/);
  assert.doesNotMatch(source, /remain available through Undo/);
});
