import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('Agent panel uses the normalized runtime/store, captured editor binding, review, cancel, and no-write boundaries', async () => {
  const source = await readFile(new URL('../src/components/AgentPanel.tsx', import.meta.url), 'utf8');
  assert.match(source, /activationState === "configuration-required"/);
  assert.match(source, /discoverAgentSkills\(\)/);
  assert.match(source, /createNativeAgentRuntime\(\)/);
  assert.match(source, /useAgentThread\(\{/);
  assert.match(source, /runtime\.startTurn\(\{/);
  assert.match(source, /retryOfTurnId/);
  assert.match(source, /upstreamThreadId: state\.runtime\.kind === "codexAppServer"/);
  assert.match(source, /const capturedBinding = binding/);
  assert.match(source, /capturedBinding\.createToolExecutor/);
  assert.match(source, /const turnId = state\.activeTurnId/);
  assert.match(source, /settleTurn\(turnId, "cancelled"/);
  assert.match(source, /runtime\.cancelTurn\(turnId\)/);
  assert.doesNotMatch(source, /activeRunId/);
  assert.match(source, /AgentChangeReview/);
  assert.match(source, /AgentThreadHistory/);
  assert.match(source, /useExternalStoreRuntime/);
  assert.match(source, /AssistantRuntimeProvider/);
  assert.match(source, /<AgentTranscript/);
  assert.match(source, /<AgentThreadHeader/);
  assert.doesNotMatch(source, /ideanote-change/);
  assert.doesNotMatch(source, /IdeaSketchAgentOperation/);
  assert.match(source, /turn\?\.binding\.documentId === binding\.document\.id/);
  assert.doesNotMatch(source, /ThreadPrimitive\.Messages/);
  assert.doesNotMatch(source, /save_file|saveWorkspaceDocument|saveStandaloneDocument/);
});
