import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

async function loadModule() {
  try {
    return await import('../src/lib/tauriBlobDownload.ts');
  } catch {
    return {};
  }
}

test('getImageBlobDownload recognizes Excalidraw PNG and SVG blob downloads', async () => {
  const { getImageBlobDownload } = await loadModule();

  assert.equal(typeof getImageBlobDownload, 'function');
  assert.deepEqual(
    getImageBlobDownload({ href: 'blob:https://idea-slide/png', download: 'diagram.png' }),
    {
      extension: 'png',
      fileName: 'diagram.png',
      mimeType: 'image/png',
    },
  );
  assert.deepEqual(
    getImageBlobDownload({ href: 'blob:https://idea-slide/svg', download: 'diagram.excalidraw.svg' }),
    {
      extension: 'svg',
      fileName: 'diagram.excalidraw.svg',
      mimeType: 'image/svg+xml',
    },
  );
  assert.equal(
    getImageBlobDownload({ href: 'https://example.com/diagram.png', download: 'diagram.png' }),
    null,
  );
});

test('persistTauriBlobDownload writes generated bytes to the selected native path', async () => {
  const { persistTauriBlobDownload } = await loadModule();

  assert.equal(typeof persistTauriBlobDownload, 'function');

  const requests = [];
  const writes = [];
  const revokedUrls = [];
  const result = await persistTauriBlobDownload(
    { href: 'blob:https://idea-slide/png', download: 'diagram.png' },
    {
      choosePath: async (request) => {
        requests.push(request);
        return '/tmp/diagram.png';
      },
      readBytes: async () => [137, 80, 78, 71],
      revokeUrl: (url) => {
        revokedUrls.push(url);
      },
      writeBytes: async (path, data) => {
        writes.push({ path, data });
      },
    },
  );

  assert.equal(result, 'saved');
  assert.deepEqual(requests, [
    {
      extension: 'png',
      fileName: 'diagram.png',
      mimeType: 'image/png',
    },
  ]);
  assert.deepEqual(writes, [
    {
      path: '/tmp/diagram.png',
      data: [137, 80, 78, 71],
    },
  ]);
  assert.deepEqual(revokedUrls, ['blob:https://idea-slide/png']);
});

test('persistTauriBlobDownload stops cleanly when the native save dialog is cancelled', async () => {
  const { persistTauriBlobDownload } = await loadModule();

  assert.equal(typeof persistTauriBlobDownload, 'function');

  let readCount = 0;
  let writeCount = 0;
  let revokeCount = 0;
  const result = await persistTauriBlobDownload(
    { href: 'blob:https://idea-slide/svg', download: 'diagram.svg' },
    {
      choosePath: async () => null,
      readBytes: async () => {
        readCount += 1;
        return [60, 115, 118, 103, 62];
      },
      revokeUrl: () => {
        revokeCount += 1;
      },
      writeBytes: async () => {
        writeCount += 1;
      },
    },
  );

  assert.equal(result, 'cancelled');
  assert.equal(readCount, 0);
  assert.equal(writeCount, 0);
  assert.equal(revokeCount, 1);
});

test('installTauriBlobDownloadBridge intercepts image blobs and delegates unrelated clicks', async () => {
  const { installTauriBlobDownloadBridge } = await loadModule();

  assert.equal(typeof installTauriBlobDownloadBridge, 'function');

  const originalClicks = [];
  const persistedDownloads = [];
  const anchorPrototype = {
    click() {
      originalClicks.push(this.href);
    },
  };
  const cleanup = installTauriBlobDownloadBridge({
    anchorPrototype,
    isTauriRuntime: () => true,
    persist: async (anchor) => {
      persistedDownloads.push({ href: anchor.href, download: anchor.download });
    },
    reportError: () => {
      assert.fail('the bridge should not report an error');
    },
  });

  anchorPrototype.click.call({
    href: 'blob:https://idea-slide/png',
    download: 'diagram.png',
  });
  anchorPrototype.click.call({
    href: 'https://example.com/',
    download: '',
  });
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.deepEqual(persistedDownloads, [
    {
      href: 'blob:https://idea-slide/png',
      download: 'diagram.png',
    },
  ]);
  assert.deepEqual(originalClicks, ['https://example.com/']);

  cleanup();
  anchorPrototype.click.call({
    href: 'blob:https://idea-slide/svg',
    download: 'diagram.svg',
  });
  assert.deepEqual(originalClicks, [
    'https://example.com/',
    'blob:https://idea-slide/svg',
  ]);
});

test('application startup installs the Tauri blob download bridge once', async () => {
  const source = await readFile(new URL('../src/main.tsx', import.meta.url), 'utf8');

  assert.match(
    source,
    /import \{ installTauriBlobDownloadBridge \} from "\.\/lib\/tauriBlobDownload";/,
  );
  assert.match(source, /installTauriBlobDownloadBridge\(\);/);
});
