import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const readSource = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('Workspace Explorer is driven by real relative paths and backend filesystem actions', async () => {
  const source = await readSource('src/components/WorkspaceExplorer.tsx');
  const styles = await readSource('src/index.css');
  assert.match(source, /WorkspaceEntry/);
  assert.doesNotMatch(source, /rootName/);
  assert.match(source, /getCreatableFileTypeDefinitions/);
  assert.match(source, /onCreateFolder/);
  assert.match(source, /onCreateDocument/);
  assert.match(source, /Promise<WorkspaceEntry \| undefined>/);
  assert.match(source, /if \(!entry\) return/);
  assert.match(source, /onRefresh/);
  assert.match(source, /onRename/);
  assert.match(source, /onMove/);
  assert.match(source, /WorkspaceDropRequest/);
  assert.match(source, /<DndContext/);
  assert.match(source, /useDroppable/);
  assert.match(source, /pointerWithin/);
  assert.match(source, /handleDragEnd/);
  assert.match(source, /workspaceParentPath/);
  assert.match(source, /data-workspace-root="true"/);
  assert.match(source, /role="toolbar"/);
  assert.match(source, /aria-label="Workspace actions"/);
  assert.match(source, /depth=\{depth\}/);
  assert.doesNotMatch(source, /depth=\{depth \+ 1\}/);
  assert.match(source, /idea-slide-workspace-action-bar/);
  assert.doesNotMatch(source, /WorkspaceRootRow/);
  assert.doesNotMatch(source, /idea-slide-workspace-root-row/);
  assert.doesNotMatch(source, /idea-slide-side-panel__header/);
  assert.match(source, /onTrash/);
  assert.match(source, /documentIndicators/);
  assert.match(source, /indicatorByPath/);
  assert.match(source, /New \{definition\.displayName\}/);
  assert.match(source, /New Folder/);
  assert.match(source, /from "lucide-react"/);
  assert.match(source, /<FilePlus2 /);
  assert.match(source, /<FolderPlus /);
  assert.match(source, /<RefreshCw /);
  assert.match(source, /<Ellipsis /);
  assert.match(source, /<ChevronsDown /);
  assert.match(source, /<ChevronsUp /);
  assert.match(source, /<ToolbarAction/);
  assert.match(source, /<TooltipProvider/);
  assert.match(source, /tooltip="New File"/);
  assert.match(source, /tooltip="New Folder"/);
  assert.match(source, /tooltip="Refresh Workspace"/);
  assert.match(source, /tooltip="Workspace Tree Actions"/);
  assert.match(source, /aria-label="Workspace Tree Actions"/);
  assert.match(source, /<DropdownMenuItem onSelect=\{expandAll\}>[\s\S]*?Expand all/);
  assert.match(source, /<DropdownMenuItem onSelect=\{collapseAll\}>[\s\S]*?Collapse all/);
  assert.doesNotMatch(source, /[＋⌑↻⌃•]/);
  assert.doesNotMatch(source, /WorkspaceResource\b/);
  assert.doesNotMatch(source, /thumbnail/i);
  const actionBarStyles = styles.match(/\.idea-slide-workspace-action-bar\s*\{([^}]*)\}/)?.[1] ?? '';
  assert.match(actionBarStyles, /display:\s*flex/);
  assert.match(actionBarStyles, /justify-content:\s*flex-start/);
  assert.doesNotMatch(actionBarStyles, /justify-content:\s*flex-end/);
  assert.match(styles, /\.idea-slide-workspace-action-bar\.is-drop-inside/);
  assert.doesNotMatch(styles, /\.idea-slide-workspace-root-row:hover\s+\.idea-slide-workspace-root-actions/);
  assert.doesNotMatch(styles, /\.idea-slide-workspace-root-actions\s*\{[\s\S]*?opacity:\s*0/);
});

test('Workspace rows keep Symlinks non-recursive and unsupported files safe', async () => {
  const source = await readSource('src/components/WorkspaceResourceRow.tsx');
  const mainRowClick = source.match(/className=\{`idea-slide-resource-main[\s\S]*?onClick=\{\(event\) => \{[\s\S]*?\}\}\s*onDoubleClick=/)?.[0] ?? '';
  assert.match(source, /from "lucide-react"/);
  assert.match(source, /<ChevronRight /);
  assert.match(source, /<ChevronDown /);
  assert.match(source, /<Folder /);
  assert.match(source, /<FolderOpen /);
  assert.match(source, /<FilePenLine /);
  assert.match(source, /<File /);
  assert.match(source, /<ExternalLink /);
  assert.match(source, /<Pencil /);
  assert.match(source, /<Trash2 /);
  assert.doesNotMatch(source, /[⌄›▾▸◇↗·✎×]/);
  assert.match(source, /entry\.kind === "symlink"/);
  assert.match(source, /Unsupported/);
  assert.match(source, /useDraggable/);
  assert.match(source, /useDroppable/);
  assert.doesNotMatch(source, /GripVertical/);
  assert.doesNotMatch(source, /idea-slide-drag-handle/);
  assert.match(source, /idea-slide-resource-main/);
  assert.match(source, /setActivatorNodeRef/);
  assert.match(source, /aria-label=\{`\$\{entry\.kind === "directory" \? "Select" : "Open"\} \$\{entry\.name\}`\}/);
  assert.match(mainRowClick, /entry\.kind === "directory" \? onSelect\(\) : onOpen\(\)/);
  assert.doesNotMatch(mainRowClick, /onSelect\(\);\s*if \(entry\.kind === "file"\) onOpen\(\)/);
  assert.match(source, /"inside"/);
  assert.doesNotMatch(source, /workspace-drop-before/);
  assert.doesNotMatch(source, /workspace-drop-after/);
  assert.doesNotMatch(source, /position: "before"/);
  assert.doesNotMatch(source, /position: "after"/);
  assert.match(source, /CSS\.Translate\.toString\(draggable\.transform\)/);
  assert.doesNotMatch(source, /scaleX\(/);
  assert.doesNotMatch(source, /scaleY\(/);
  assert.match(source, /F2/);
  assert.match(source, /getWorkspaceRenameSelectionEnd/);
  assert.match(source, /setSelectionRange\(0, getWorkspaceRenameSelectionEnd\(entry\.name, entry\.kind\)\)/);
  assert.doesNotMatch(source, /inputRef\.current\?\.select\(\)/);
  assert.match(source, /ArrowRight/);
  assert.match(source, /Move .* to Trash/);
  assert.match(source, /isDocumentActive/);
  assert.match(source, /documentStatus/);
  assert.match(source, /idea-slide-resource-status/);
  assert.match(source, /documentStatusClassName/);
  assert.match(source, /\["conflict", "error", "invalid", "missing", "root-missing"\]/);
  assert.match(source, /documentStatus === "missing" \|\| documentStatus === "root-missing"/);
  assert.doesNotMatch(source, /WORKSPACE_DRAG_MIME/);
  assert.doesNotMatch(source, /draggable=/);
  assert.doesNotMatch(source, /dataTransfer/);
  assert.doesNotMatch(source, /onDrag(?:Start|Over|Leave|End|Drop)/);
});

test('Editor shell preserves bounded resize and shows Explorer only for Workspace sessions', async () => {
  const source = await readSource('src/components/EditorLayout.tsx');
  const explorer = await readSource('src/components/WorkspaceExplorer.tsx');
  assert.match(source, /state\.workspace &&/);
  assert.match(source, /WORKSPACE_PANEL_MIN_WIDTH/);
  assert.match(source, /WORKSPACE_PANEL_MAX_WIDTH/);
  assert.match(source, /clampWorkspacePanelWidth/);
  assert.match(source, /<ResizableDivider/);
  assert.match(source, /WorkspaceStatusNotice/);
  assert.match(explorer, /projectVisibleWorkspaceRows/);
});
