import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const readSource = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('Workspace Explorer is driven by real relative paths and backend filesystem actions', async () => {
  const source = await readSource('src/components/WorkspaceExplorer.tsx');
  assert.match(source, /WorkspaceEntry/);
  assert.match(source, /rootName/);
  assert.match(source, /getCreatableFileTypeDefinitions/);
  assert.match(source, /onCreateFolder/);
  assert.match(source, /onCreateDocument/);
  assert.match(source, /onRefresh/);
  assert.match(source, /onRename/);
  assert.match(source, /onMove/);
  assert.match(source, /WorkspaceDropRequest/);
  assert.match(source, /<DndContext/);
  assert.match(source, /useDroppable/);
  assert.match(source, /pointerWithin/);
  assert.match(source, /handleDragEnd/);
  assert.match(source, /workspaceParentPath/);
  assert.match(source, /Move to Workspace root/);
  assert.match(source, /onTrash/);
  assert.match(source, /documentIndicators/);
  assert.match(source, /indicatorByPath/);
  assert.match(source, /New \{definition\.displayName\}/);
  assert.match(source, /New Folder/);
  assert.match(source, /from "lucide-react"/);
  assert.match(source, /<FilePlus2 /);
  assert.match(source, /<FolderPlus /);
  assert.match(source, /<RefreshCw /);
  assert.match(source, /<Ellipsis /);
  assert.match(source, /<ChevronsDown /);
  assert.match(source, /<ChevronsUp /);
  assert.match(source, /<ToolbarAction/);
  assert.match(source, /<TooltipProvider/);
  assert.match(source, /tooltip="New File"/);
  assert.match(source, /tooltip="New Folder"/);
  assert.match(source, /tooltip="Refresh Workspace"/);
  assert.match(source, /tooltip="Workspace Tree Actions"/);
  assert.match(source, /aria-label="Workspace Tree Actions"/);
  assert.match(source, /<DropdownMenuItem onSelect=\{expandAll\}>[\s\S]*?Expand all/);
  assert.match(source, /<DropdownMenuItem onSelect=\{collapseAll\}>[\s\S]*?Collapse all/);
  assert.doesNotMatch(source, /[＋⌑↻⌃•]/);
  assert.doesNotMatch(source, /WorkspaceResource\b/);
  assert.doesNotMatch(source, /thumbnail/i);
});

test('Workspace rows keep Symlinks non-recursive and unsupported files safe', async () => {
  const source = await readSource('src/components/WorkspaceResourceRow.tsx');
  assert.match(source, /from "lucide-react"/);
  assert.match(source, /<ChevronRight /);
  assert.match(source, /<ChevronDown /);
  assert.match(source, /<Folder /);
  assert.match(source, /<FolderOpen /);
  assert.match(source, /<FilePenLine /);
  assert.match(source, /<File /);
  assert.match(source, /<ExternalLink /);
  assert.match(source, /<Pencil /);
  assert.match(source, /<Trash2 /);
  assert.doesNotMatch(source, /[⌄›▾▸◇↗·✎×]/);
  assert.match(source, /entry\.kind === "symlink"/);
  assert.match(source, /Unsupported/);
  assert.match(source, /useDraggable/);
  assert.match(source, /useDroppable/);
  assert.match(source, /<GripVertical /);
  assert.match(source, /setActivatorNodeRef/);
  assert.match(source, /aria-label=\{`Drag \$\{entry\.name\}`\}/);
  assert.match(source, /"inside"/);
  assert.doesNotMatch(source, /workspace-drop-before/);
  assert.doesNotMatch(source, /workspace-drop-after/);
  assert.doesNotMatch(source, /position: "before"/);
  assert.doesNotMatch(source, /position: "after"/);
  assert.match(source, /CSS\.Translate\.toString\(draggable\.transform\)/);
  assert.doesNotMatch(source, /scaleX\(/);
  assert.doesNotMatch(source, /scaleY\(/);
  assert.match(source, /F2/);
  assert.match(source, /ArrowRight/);
  assert.match(source, /Move .* to Trash/);
  assert.match(source, /isDocumentActive/);
  assert.match(source, /documentStatus/);
  assert.match(source, /idea-slide-resource-status/);
  assert.match(source, /documentStatusClassName/);
  assert.match(source, /\["conflict", "error", "invalid", "missing", "root-missing"\]/);
  assert.match(source, /documentStatus === "missing" \|\| documentStatus === "root-missing"/);
  assert.doesNotMatch(source, /WORKSPACE_DRAG_MIME/);
  assert.doesNotMatch(source, /draggable=/);
  assert.doesNotMatch(source, /dataTransfer/);
  assert.doesNotMatch(source, /onDrag(?:Start|Over|Leave|End|Drop)/);
});

test('Editor shell preserves bounded resize and shows Explorer only for Workspace sessions', async () => {
  const source = await readSource('src/components/EditorLayout.tsx');
  const explorer = await readSource('src/components/WorkspaceExplorer.tsx');
  assert.match(source, /state\.workspace &&/);
  assert.match(source, /WORKSPACE_PANEL_MIN_WIDTH/);
  assert.match(source, /WORKSPACE_PANEL_MAX_WIDTH/);
  assert.match(source, /clampWorkspacePanelWidth/);
  assert.match(source, /<ResizableDivider/);
  assert.match(source, /WorkspaceStatusNotice/);
  assert.match(explorer, /projectVisibleWorkspaceRows/);
});
